version: '3.5'

services:
  php:
    image: karllhughes/laravel-kubernetes:latest
    restart: always
    ports:
      - 8000:80
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=travellist
      - MYSQL_USER=travellist_user
      - MYSQL_PASSWORD=password
